### ISSUE TITLE
[Error] An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by OHHAKO** [subply/subply#11]
- 유튜브 플레이어 호출 시
An accessor cannot be declared in an ambient context. 이라는 오류가 콘솔에 뜹니다.
- videoId 타입 문제인가 싶은데 string 타입 선언 해 놓았는데도 오류가 발생합니다!
- 한번 확인 부탁드려요 :)

**Comment by forbid403** [comment]
https://github.com/microsoft/TypeScript/issues/33939
타입스크립트, 앵귤러 버젼 문제였습니다.
>    "typescript": "^3.8.3",
>    "@angular/cli": "~9.1.6"

로 업데이트 했습니다.
`package.json`참고 바랍니다!
