### ISSUE TITLE
[bug] Angular cli , package dependency 

### ISSUE THREAD

**Issue by OHHAKO** [subply/subply#12]
1. master 브랜치 버전에서 `ng serve` 실행 후 
`Cannot find moudle '@angular/youtube-player'.` 에러 발생
=> `ng install @angular/youtube-player` 해결

2. https://github.com/subply/subply/issues/11
버전 수정 및 `npm install` `ng serve`실행 후 에러 발생

 `An unhandled exception occurred: Could not find the implementation for builder @angular-devkit/build-angular:dev-server
See "C:\Users\khk05\AppData\Local\Temp\ng-c5wCA8\angular-errors.log" for further details.` 에러 발생

**Comment by forbid403** [comment]
1. 이 오류는 모듈 설치 하면 해결됩니다
2. https://github.com/angular/angular-cli/issues/15063 여기 참고하시면 될 것 같습니다!

**Comment by OHHAKO** [comment]
2. Angular 버전과 관련된 패키지를 Angular-cli  9.1.7이 지원하는 패키지로 모두 변경시켰더니 Angular버전이 업그레이드 되었어요.
(참고 https://dschci.tistory.com/103)

저는 업그레이드 할때 관련 패키지를 하나씩 설치해주었는데 원하는 Angular버전으로 한번에 업데이트 해주는 기능을 지원하면 좋을 것 같네요.
