### ISSUE TITLE
Q. 컴포넌트 추가 및 화면 출력

### ISSUE THREAD

**Issue by OHHAKO** [subply/subply#3]
- 컴포넌트 생성
- 라우팅 등록
- 메뉴 추가

필요한 컴포넌트는 도막님이 생각하는 웹 스토리보드를 참고하거나
새롭게  추가하면 좋을것 같아요:)

**Comment by forbid403** [comment]
### 라우팅, 컴포넌트, 메뉴 추가
- 마이페이지, 랭킹 페이지

이렇게 진행 하겠습니다!

**Comment by forbid403** [comment]
#4 리뷰 부탁드립니다
