### ISSUE TITLE
[TRANSLATE] VIdeo 제어 에러

### ISSUE THREAD

**Issue by OHHAKO** [subply/subply#44]
번역 블록 클릭시 영상 제어가 안되는 문제를 발견했습니다.

**Comment by forbid403** [comment]
저는 정상 작동 됩니다.
어떤 문제가 있나요?

**Comment by OHHAKO** [comment]
translate 컴포넌트로 전환되고 나서 script 블록을 클릭하면 영상에 무한 로딩이 걸려요.

**Comment by forbid403** [comment]
확인해본 결과
raw-script 컴포넌트에서 script가 float형식이 아닌 string으로 변환되어서 동작이 되지 않았습니다
string으로 바꾸신 이유가 있을까요??

**Comment by OHHAKO** [comment]
iso Time으로 포맷하는 메서드가 결과값을 String으로 반환해요.
뷰 출력시 iso Time으로 포맷되어있어야 하고 srt 파일의 텍스트 포맷도 iso Time 이어야해요. 그래서 Script 인터페이스 변수 start, end 를 string으로 바꾸었어요.
